version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vk-io
    versions:
    - 4.1.3
    - 4.1.4
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
